services:
  db:
    image: mysql:lts
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: limas
      MYSQL_USER: limas
      MYSQL_PASSWORD: limas
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
      start_period: 10s
      interval: 10s
  limas:
    image: n404/limas-docker
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - 8080:80
    volumes:
      - ./data:/var/www/html/data
    environment:
      APP_ENV: prod
      DATABASE_URL: mysql://limas:limas@db:3306/limas?serverVersion=5.7.9&charset=utf8mb4
  redis:
    image: redis:7-alpine
    restart: unless-stopped